dist: xenial
sudo: required
language: c
before_install:
  - sudo apt-get update -q
  - sudo apt install dash bash ash ksh zsh tcsh csh rc
script: 
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
  - test/ttest.sh

